// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    hub_hours: {
        name: "hub_hours";
        parameters: {
          /** STRING - use sql.string() */
          hub: SQLStringMarker;
          /** STRING - use sql.string() */
          day_type: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          hour: number;
          /** @sqlType DOUBLE */
          avg_pings: number;
          /** @sqlType BIGINT */
          departures: number;
          /** @sqlType BIGINT */
          bus_departures: number;
          /** @sqlType BIGINT */
          skytrain_departures: number;
          /** @sqlType BIGINT */
          seabus_departures: number;
          /** @sqlType BIGINT */
          lines_running: number;
          /** @sqlType STRING */
          status: string;
          /** @sqlType STRING */
          time_period: string;
          /** @sqlType DOUBLE */
          max_peak_load_factor: number;
          /** @sqlType STRING */
          most_crowded_line: string;
        }>;
      };
    hub_overview: {
        name: "hub_overview";
        parameters: {
          /** STRING - use sql.string() */
          hub: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          days: number;
          /** @sqlType BIGINT */
          visits: number;
          /** @sqlType DOUBLE */
          visitor_share: number;
          /** @sqlType INT */
          surge_days: number;
          /** @sqlType STRING */
          top_surge_date: string;
          /** @sqlType DOUBLE */
          top_surge_index: number;
          /** @sqlType DOUBLE */
          transfer_share: number;
          /** @sqlType STRING */
          worst_line: string;
          /** @sqlType DOUBLE */
          worst_line_overcrowded_pct: number;
          /** @sqlType STRING */
          peak_load_where: string;
          /** @sqlType DOUBLE */
          peak_load_pct: number;
        }>;
      };
    origin_access: {
        name: "origin_access";
        parameters: {
          /** STRING - use sql.string() */
          hub: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          origin: string;
          /** @sqlType DOUBLE */
          share_pct: number;
          /** @sqlType STRING */
          access_type: string;
          /** @sqlType STRING */
          direct_lines: string;
        }>;
      };
    recommendations: {
        name: "recommendations";
        parameters: {
          /** STRING - use sql.string() */
          hub: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          priority: number;
          /** @sqlType STRING */
          category: string;
          /** @sqlType STRING */
          recommendation: string;
          /** @sqlType STRING */
          evidence: string;
        }>;
      };
    route_crowding: {
        name: "route_crowding";
        parameters: {
          /** STRING - use sql.string() */
          hub: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          line_name: string;
          /** @sqlType DOUBLE */
          pct_trips_overcrowded: number;
          /** @sqlType DOUBLE */
          avg_peak_load_factor: number;
          /** @sqlType DOUBLE */
          pct_bunching: number;
        }>;
      };
    weekly_trend: {
        name: "weekly_trend";
        parameters: {
          /** STRING - use sql.string() */
          hub: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          week: string;
          /** @sqlType DOUBLE */
          visits: number;
          /** @sqlType DOUBLE */
          forecast: number;
        }>;
      };
  }
}
